# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-06-06 15:25:26
"""
import arcpy
from sys import argv

def Model(phy_Y23_24_L710="phy_Y23-24_L710"):  # Alternative_Buffer_GT_2024

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    Distance_value_or_field_ = "-0.7 Meters"

    # Process: Buffer + (Buffer) (analysis)
    Buffer_by_row = "D:\\RSG Dropbox\\RSG Dropbox\\Gil Thompson\\2024\\04- Others\\03- Test_Thermal_Cal\\Default.gdb\\Buffer_by_row"
    arcpy.analysis.Buffer(in_features=phy_Y23_24_L710.__str__().format(**locals(),**globals()), out_feature_class=Buffer_by_row, buffer_distance_or_field="0.2 Meters", dissolve_option="LIST", dissolve_field=["row"])

    # Process: Buffer - (Buffer) (analysis)
    Buffer_by_row_ = "D:\\RSG Dropbox\\RSG Dropbox\\Gil Thompson\\2024\\04- Others\\03- Test_Thermal_Cal\\Default.gdb\\Buffer_by_row_"
    arcpy.analysis.Buffer(in_features=Buffer_by_row, out_feature_class=Buffer_by_row_, buffer_distance_or_field=Distance_value_or_field_)

    # Process: Intersect (Intersect) (analysis)
    phy_Y2324_L710_Buf_Intersect = "D:\\RSG Dropbox\\RSG Dropbox\\Gil Thompson\\2024\\04- Others\\03- Test_Thermal_Cal\\Default.gdb\\phy_Y2324_L710_Buf_Intersect"
    arcpy.analysis.Intersect(in_features=[[Buffer_by_row_, ""], [phy_Y23_24_L710, ""]], out_feature_class=phy_Y2324_L710_Buf_Intersect)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="D:\\RSG Dropbox\\RSG Dropbox\\Gil Thompson\\2024\\04- Others\\03- Test_Thermal_Cal\\Default.gdb", workspace="D:\\RSG Dropbox\\RSG Dropbox\\Gil Thompson\\2024\\04- Others\\03- Test_Thermal_Cal\\Default.gdb"):
        Model(*argv[1:])
