# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-11-21 20:49:45
"""
import arcpy
from arcpy.ia import *
from sys import argv

#For inline variable substitution, parameters passed as a String are evaluated using locals(), globals() and isinstance(). To override, substitute values directly.
def Model6(small_raster="8_4_EYTBWB5IR_06_6044__BwY24_5Irr_rededge_20240314_ndvi.tif", add_geometry="D:\\OneDrive - CIMMYT\\Desktop\\Bw_PcsY23\\Bw_PcsY23.gdb\\vegetationpoints"):  # Get_point_4_pixels

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Check out any necessary licenses.
    arcpy.CheckOutExtension("spatial")
    arcpy.CheckOutExtension("ImageAnalyst")

    arcpy.ImportToolbox(r"c:\users\ithompson\appdata\local\programs\arcgis\pro\Resources\ArcToolbox\toolboxes\Data Management Tools.tbx")

    # Process: Copy Raster (Copy Raster) (management)
    soilmask = "D:\\OneDrive - CIMMYT\\Desktop\\Bw_PcsY23\\Bw_PcsY23.gdb\\soilmask"
    arcpy.management.CopyRaster(in_raster=small_raster.__str__().format(**locals(),**globals())if isinstance(small_raster, str) else small_raster, out_rasterdataset=soilmask, format="GRID")

    # Process: Raster Calculator (Raster Calculator) (ia)
    vegetationraster = "D:\\OneDrive - CIMMYT\\Desktop\\Bw_PcsY23\\Bw_PcsY23.gdb\\vegetationraster"
    Raster_Calculator = vegetationraster
    vegetationraster = (Con(soilmask > 0.8, 1, 0))  * small_raster
    vegetationraster.save(Raster_Calculator)


    # Process: Raster to Point (Raster to Point) (conversion)
    vegetationpoints = "D:\\OneDrive - CIMMYT\\Desktop\\Bw_PcsY23\\Bw_PcsY23.gdb\\vegetationpoints"
    with arcpy.EnvManager(outputMFlag="Disabled", outputZFlag="Disabled"):
        arcpy.conversion.RasterToPoint(in_raster=vegetationraster, out_point_features=vegetationpoints)

    # Process: Add Field (Add Field) (management)
    add_field_x = arcpy.management.AddField(in_table=vegetationpoints, field_name="Lat", field_type="DOUBLE")[0]

    # Process: Add Field (2) (Add Field) (management)
    add_field_y = arcpy.management.AddField(in_table=add_field_x, field_name="Lng", field_type="DOUBLE")[0]

    # Process: Calculate Geometry Attributes (Calculate Geometry Attributes) (management)
    add_geometry = arcpy.management.CalculateGeometryAttributes(in_features=add_field_y, geometry_property=[["Lat", "POINT_X"], ["Lng", "POINT_Y"]], coordinate_system="PROJCS[\"WGS_1984_UTM_Zone_12N\",GEOGCS[\"GCS_WGS_1984\",DATUM[\"D_WGS_1984\",SPHEROID[\"WGS_1984\",6378137.0,298.257223563]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Transverse_Mercator\"],PARAMETER[\"False_Easting\",500000.0],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-111.0],PARAMETER[\"Scale_Factor\",0.9996],PARAMETER[\"Latitude_Of_Origin\",0.0],UNIT[\"Meter\",1.0]]")[0]

    # Process: Parse Path (Parse Path) (mb)
    Path, Name, Extension, Workspace_Name = arcpy.mb.ParsePathExt(in_data_element=small_raster.__str__().format(**locals(),**globals())if isinstance(small_raster, str) else small_raster)

    # Process: Calculate Value (Calculate Value) ()
    Name_ = "r"+"Name".replace("_","").replace(".tif", "").replace("--", "")+".shp"

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="D:\\OneDrive - CIMMYT\\Desktop\\Bw_PcsY23\\Bw_PcsY23.gdb", workspace="D:\\OneDrive - CIMMYT\\Desktop\\Bw_PcsY23\\Bw_PcsY23.gdb"):
        Model6(*argv[1:])
